# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[❯❯❯](bold green)'

[hostname]
style = "bold #bd93f9"
ssh_only = false

[username]
format = "[$user]($style) @ ($hostname)"
show_always = true
style_user = "bold #8be9fd"
